### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tonydub** [deluan/navidrome#48]
**Version affected:** v0.4.1 (22d57a7)

**Description:**
Running navidrome with _docker-compose_ with log level DEBUG and scan music folder mounted with [_goofys_](https://github.com/kahing/goofys)

```bash
$ docker-compose logs -f navidrome
navidrome_1              | panic: runtime error: invalid memory address or nil pointer dereference
navidrome_1              | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x922c97]
navidrome_1              | 
navidrome_1              | goroutine 11 [running]:
navidrome_1              | github.com/deluan/navidrome/scanner.(*Metadata).Size(...)
navidrome_1              | 	/src/scanner/metadata_ffmpeg.go:43
navidrome_1              | github.com/deluan/navidrome/scanner.(*TagScanner).toMediaFile(0xc00017e6f0, 0xc000285bc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
navidrome_1              | 	/src/scanner/tag_scanner.go:245 +0x487
navidrome_1              | github.com/deluan/navidrome/scanner.(*TagScanner).loadTracks(0xc00017e6f0, 0xc00040ac80, 0x40, 0x1937c38, 0x0, 0x0, 0x0, 0x0)
navidrome_1              | 	/src/scanner/tag_scanner.go:216 +0x125
navidrome_1              | github.com/deluan/navidrome/scanner.(*TagScanner).processChangedDir(0xc00017e6f0, 0x0, 0x0, 0xc00040ac80, 0x40, 0xc00031f8c0, 0xc00031f800, 0x0, 0x0)
navidrome_1              | 	/src/scanner/tag_scanner.go:154 +0x351
navidrome_1              | github.com/deluan/navidrome/scanner.(*TagScanner).Scan(0xc00017e6f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00003e5e8)
navidrome_1              | 	/src/scanner/tag_scanner.go:61 +0x3ab
navidrome_1              | github.com/deluan/navidrome/scanner.(*Scanner).Rescan(0xc000186e00, 0xc00002404f, 0x6, 0xc000001b00, 0x0, 0x1)
navidrome_1              | 	/src/scanner/scanner.go:37 +0x18e
navidrome_1              | github.com/deluan/navidrome/scanner.(*Scanner).RescanAll(0xc000186e00, 0x0, 0x5, 0xc00003e7a8)
navidrome_1              | 	/src/scanner/scanner.go:50 +0xcf
navidrome_1              | github.com/deluan/navidrome/server.(*Server).initScanner.func1(0xc000186ea0, 0x34630b8a000)
navidrome_1              | 	/src/server/server.go:79 +0x5a
navidrome_1              | created by github.com/deluan/navidrome/server.(*Server).initScanner
navidrome_1              | 	/src/server/server.go:76 +0x172
```

**Comment by deluan** [comment]
Thanks for the report.

This seems to be caused by a file that could not be parsed by the Scanner. I just released a fix (0.4.2) that would skip such files, but will output an Error log message.

Can you please try with this new version, and look for any Error messages during the scan phase? Let me know what errors you get.

If it still gives you panic errors, please re-run with loglevel=TRACE, and post the log again including a few lines before the panic line.

**Comment by tonydub** [comment]
No more panic generated while scanning files

Thank you.

**Comment by deluan** [comment]
It is very possible that now one (or more) files from your library are being skipped. Did you check for errors in the log after the scan was complete? It should give errors for unparseable files (the original issue)
